


/* Create Tables */
DROP TABLE IF EXISTS DATELOOKUP;
CREATE TABLE "DATELOOKUP"
(
	"DATETIME" DateTime NOT NULL,
	"WEEK" Integer NOT NULL,
 PRIMARY KEY ("DATETIME")
);

DROP TABLE IF EXISTS TRANSACTIONARCHIVES;
CREATE TABLE "TRANSACTIONARCHIVES"
(
	"ARCHIVE_ID" Integer NOT NULL,
	"NAME" Varchar(50) NOT NULL,
	"ADDED" DateTime NOT NULL,
	"USERNAME" Varchar(255) NOT NULL,
	"FINISHED" DateTime,
	"STATUS" Varchar(100),
	"ARCHIVETABLES" Text,
 PRIMARY KEY ("ARCHIVE_ID")
);

DROP TABLE IF EXISTS TRANSACTIONATTRIBUTES;
CREATE TABLE "TRANSACTIONATTRIBUTES"
(
	"TRANSACTION_GUID" Varchar(36) NOT NULL,
	"ATTRIBUTE" Varchar(50) NOT NULL,
	"VALUE" Varchar(255),
 PRIMARY KEY ("TRANSACTION_GUID","ATTRIBUTE")
);

DROP TABLE IF EXISTS TRANSACTIONFILES;
CREATE TABLE "TRANSACTIONFILES"
(
	"FILE_ID" Integer NOT NULL,
	"NAME" Varchar(50) NOT NULL,
	"ADDED" DateTime NOT NULL,
	"USERNAME" Varchar(255) NOT NULL,
	"FINISHED" DateTime,
	"STATUS" Varchar(100),
	"FILEPATHS" Text,
 PRIMARY KEY ("FILE_ID")
);

DROP TABLE IF EXISTS TRANSACTIONS;
CREATE TABLE "TRANSACTIONS"
(
	"TRANSACTION_GUID" Varchar(36) NOT NULL,
	"PARENT_GUID" Varchar(36),
	"ORGANISATION" Varchar(50) NOT NULL,
	"TYPE" Varchar(50) NOT NULL,
	"DATETIME" DateTime NOT NULL,
	"USERNAME" Varchar(255) NOT NULL,
	"CONTEXT_USER" Varchar(255) NOT NULL,
	"REFERENCE" Varchar(50),
	"QUANTITY" Integer NOT NULL Default 1,
	"STATE" Integer NOT NULL Default 1,
	"APPLICATIONID" Varchar(50) NOT NULL,
	"ORGANIZATION_GUID" Varchar(36) NOT NULL,
	"CHANNEL_GUID" Varchar(36),
 PRIMARY KEY ("TRANSACTION_GUID")
);

DROP TABLE IF EXISTS TRANSACTIONTOTALDAYS;
CREATE TABLE "TRANSACTIONTOTALDAYS"
(
	"DATETIME" DateTime NOT NULL,
	"TYPE" Varchar(50) NOT NULL,
	"ORGANISATION" Varchar(50) NOT NULL,
	"APPLICATIONID" Varchar(50) NOT NULL,
	"AMOUNT" Integer NOT NULL Default 0,
	"ORGANIZATION_GUID" Varchar(36) NOT NULL,
 PRIMARY KEY ("DATETIME","TYPE","ORGANISATION","APPLICATIONID")
);

DROP TABLE IF EXISTS TRANSACTIONTOTALMONTHS;
CREATE TABLE "TRANSACTIONTOTALMONTHS"
(
	"DATETIME" DateTime NOT NULL,
	"TYPE" Varchar(50) NOT NULL,
	"ORGANISATION" Varchar(50) NOT NULL,
	"APPLICATIONID" Varchar(50) NOT NULL,
	"AMOUNT" Integer Default 0,
	"MONTH" Integer NOT NULL,
	"YEAR" Integer NOT NULL,
	"ORGANIZATION_GUID" Varchar(36) NOT NULL,
 PRIMARY KEY ("DATETIME","TYPE","ORGANISATION","APPLICATIONID")
);

DROP TABLE IF EXISTS TRANSACTIONTOTALWEEKS;
CREATE TABLE "TRANSACTIONTOTALWEEKS"
(
	"DATETIME" DateTime NOT NULL,
	"TYPE" Varchar(50) NOT NULL,
	"ORGANISATION" Varchar(50) NOT NULL,
	"APPLICATIONID" Varchar(50) NOT NULL,
	"AMOUNT" Integer NOT NULL Default 0,
	"WEEK" Integer NOT NULL,
	"YEAR" Integer NOT NULL,
	"ORGANIZATION_GUID" Varchar(36) NOT NULL,
 PRIMARY KEY ("DATETIME","TYPE","ORGANISATION","APPLICATIONID")
);

DROP TABLE IF EXISTS TRANSACTIONTRANSFORMATIONS;
CREATE TABLE "TRANSACTIONTRANSFORMATIONS"
(
	"CLASS" Varchar(255) NOT NULL,
	"ACTIVE" Integer NOT NULL Default 1,
	"LASTUPDATE" DateTime,
	"COUNT" Bigint NOT NULL Default 1,
 PRIMARY KEY ("CLASS")
);

DROP TABLE IF EXISTS TRANSACTIONTYPES;
CREATE TABLE "TRANSACTIONTYPES"
(
	"TYPE" Varchar(50) NOT NULL,
	"ORGANISATION" Varchar(50) NOT NULL,
	"APPLICATIONID" Varchar(50) NOT NULL,
	"VISIBLE" Integer NOT NULL Default 0,
	"ACTIVE" Integer NOT NULL Default 0,
	"DATETIME" DateTime NOT NULL,
	"DESCRIPTION" Varchar(100),
	"ORGANIZATION_GUID" Varchar(36) NOT NULL,
 PRIMARY KEY ("TYPE","ORGANISATION","APPLICATIONID")
);

DROP TABLE IF EXISTS METRICS_ORGANIZATIONS;
CREATE TABLE "METRICS_ORGANIZATIONS"
(
	"ORGANIZATION_GUID" Varchar(36) NOT NULL,
	"ORGANIZATION_NAME" Varchar(50) NOT NULL,
	"ORGANIZATION_FULL_NAME" Varchar(200),
	"LANGUAGE_CODE" Varchar(10),
	"CHANNEL_GUID" Varchar(36) NOT NULL,
 PRIMARY KEY ("ORGANIZATION_GUID")
);

DROP TABLE IF EXISTS METRICS_CHANNELS;
CREATE TABLE "METRICS_CHANNELS"
(
	"CHANNEL_GUID" Varchar(36) NOT NULL,
	"CHANNEL_NAME" Varchar(50) NOT NULL,
	"CHANNEL_DESCR" Text,
	"ORGANIZATION_GUID" Varchar(36),
 PRIMARY KEY ("CHANNEL_GUID")
);


/* Create Alternate Keys */


/* Create Indexes */
CREATE INDEX "IX_WEEK" ON "DATELOOKUP"  ("WEEK");
CREATE INDEX "IX_TRAAPP" ON "TRANSACTIONS"  ("APPLICATIONID");
CREATE INDEX "IX_TRADATE" ON "TRANSACTIONS"  ("DATETIME");
CREATE INDEX "IX_TRAORG" ON "TRANSACTIONS"  ("ORGANISATION");
CREATE INDEX "IX_TRAPARENT" ON "TRANSACTIONS"  ("PARENT_GUID");
CREATE INDEX "IX_TRATYPE" ON "TRANSACTIONS"  ("TYPE");
CREATE INDEX "IX_TOTDAYAPP" ON "TRANSACTIONTOTALDAYS"  ("APPLICATIONID");
CREATE INDEX "IX_TOTDAYDATE" ON "TRANSACTIONTOTALDAYS"  ("DATETIME");
CREATE INDEX "IX_TOTDAYORG" ON "TRANSACTIONTOTALDAYS"  ("ORGANISATION");
CREATE INDEX "IX_TOTDAYTYPE" ON "TRANSACTIONTOTALDAYS"  ("TYPE");
CREATE INDEX "IX_TOTMONTHAPP" ON "TRANSACTIONTOTALMONTHS"  ("APPLICATIONID");
CREATE INDEX "IX_TOTMONTHDATE" ON "TRANSACTIONTOTALMONTHS"  ("DATETIME");
CREATE INDEX "IX_TOTMONTHORG" ON "TRANSACTIONTOTALMONTHS"  ("ORGANISATION");
CREATE INDEX "IX_TOTMONTHTYPE" ON "TRANSACTIONTOTALMONTHS"  ("TYPE");
CREATE INDEX "IX_TOTWEEKDATE" ON "TRANSACTIONTOTALWEEKS"  ("DATETIME");
CREATE INDEX "IX_TOTWEEKAPP" ON "TRANSACTIONTOTALWEEKS"  ("APPLICATIONID");
CREATE INDEX "IX_TOTWEEKORG" ON "TRANSACTIONTOTALWEEKS"  ("ORGANISATION");
CREATE INDEX "IX_TOTWEEKTYPE" ON "TRANSACTIONTOTALWEEKS"  ("TYPE");
CREATE INDEX "IX_TYPEACTIVE" ON "TRANSACTIONTYPES"  ("ACTIVE");
CREATE INDEX "IX_SUBOVERVIEW" ON "TRANSACTIONTYPES"  ("ORGANISATION","APPLICATIONID","TYPE","VISIBLE");
CREATE INDEX "IX_TYPEVISIBLE" ON "TRANSACTIONTYPES"  ("VISIBLE");
CREATE INDEX "IX_SUBTOTALS" ON "TRANSACTIONTYPES"  ("ORGANISATION","APPLICATIONID","TYPE","ACTIVE");
CREATE UNIQUE INDEX "IX_METRICS_ORGANIZATIONS_NAME" ON "METRICS_ORGANIZATIONS"  ("ORGANIZATION_NAME");
CREATE UNIQUE INDEX "IX_METRICS_ORGANIZATION_BY_METRICS_CHANNELS" ON "METRICS_ORGANIZATIONS"  ("CHANNEL_GUID","ORGANIZATION_GUID");
CREATE UNIQUE INDEX "IX_METRICS_CHANNEL_NAME" ON "METRICS_CHANNELS"  ("CHANNEL_NAME");
CREATE INDEX "IX_METRICS_CHANNEL_ADMIN_OFFICE" ON "METRICS_CHANNELS"  ("ORGANIZATION_GUID");


/* Create Foreign Keys */

ALTER TABLE "TRANSACTIONATTRIBUTES" ADD Constraint "FK_TRANSACTIONATTRIBUTES_TRANSACTIONS" FOREIGN KEY ("TRANSACTION_GUID") REFERENCES "TRANSACTIONS" ("TRANSACTION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "TRANSACTIONTOTALWEEKS" ADD Constraint "FK_TRANSACTIONTOTALWEEKS_METRICS_ORGANIZATIONS" FOREIGN KEY ("ORGANIZATION_GUID") REFERENCES "METRICS_ORGANIZATIONS" ("ORGANIZATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "TRANSACTIONTOTALDAYS" ADD Constraint "FK_TRANSACTIONTOTALDAYS_METRICS_ORGANIZATIONS" FOREIGN KEY ("ORGANIZATION_GUID") REFERENCES "METRICS_ORGANIZATIONS" ("ORGANIZATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "TRANSACTIONTOTALMONTHS" ADD Constraint "FK_TRANSACTIONTOTALMONTHS_METRICS_ORGANIZATIONS" FOREIGN KEY ("ORGANIZATION_GUID") REFERENCES "METRICS_ORGANIZATIONS" ("ORGANIZATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "TRANSACTIONTYPES" ADD Constraint "FK_TRANSACTIONTYPES_METRICS_ORGANIZATIONS" FOREIGN KEY ("ORGANIZATION_GUID") REFERENCES "METRICS_ORGANIZATIONS" ("ORGANIZATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "TRANSACTIONS" ADD Constraint "FK_TRANSACTIONS_METRICS_ORGANIZATIONS" FOREIGN KEY ("ORGANIZATION_GUID") REFERENCES "METRICS_ORGANIZATIONS" ("ORGANIZATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "METRICS_ORGANIZATIONS" ADD Constraint "FK_METRICS_ORGANIZATIONS_METRICS_CHANNELS" FOREIGN KEY ("CHANNEL_GUID") REFERENCES "METRICS_CHANNELS" ("CHANNEL_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "TRANSACTIONS" ADD Constraint "FK_METRICS_CHANNELS_TRANSACTIONS" FOREIGN KEY ("CHANNEL_GUID") REFERENCES "METRICS_CHANNELS" ("CHANNEL_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;





/* Create Tables */
DROP TABLE IF EXISTS ERRORS;
CREATE TABLE "ERRORS"
(
	"MESSAGE_GUID" Varchar(36) NOT NULL,
	"EXCEPTION_ID" Varchar(36) NOT NULL,
	"SEQUENCE_NUMBER" Smallint NOT NULL,
	"ERROR_CODE" Varchar(150),
	"MESSAGE" Varchar(255),
	"DETAILS" Text,
	"ORGANIZATION_CN" Varchar(50),
	"USER_CN" Varchar(50),
	"OBJECT_GUID" Varchar(36),
	"CREATION_DATE" DateTime NOT NULL,
	"QUALIFIED_CLASS_NAME" Varchar(200),
 PRIMARY KEY ("MESSAGE_GUID")
);

DROP TABLE IF EXISTS LANGUAGES;
CREATE TABLE "LANGUAGES"
(
	"LANGUAGE_CODE" Varchar(10) NOT NULL,
 PRIMARY KEY ("LANGUAGE_CODE")
);

DROP TABLE IF EXISTS PARAMETERS;
CREATE TABLE "PARAMETERS"
(
	"PARAMETER_GUID" Varchar(36) NOT NULL,
	"PARAMETER_NAME" Varchar(100) NOT NULL,
	"ORGANIZATION_NAME" Varchar(50),
	"PARAMETER_TYPE" Smallint NOT NULL,
	"PARAMETER_VALUE" Varchar(255),
	"DESCR" Varchar(255),
	"CHANGE_TYPE" Smallint NOT NULL,
	"DATE_MODIFIED" DateTime,
	"MODIFIED_BY_DN" Varchar(200) NOT NULL,
 PRIMARY KEY ("PARAMETER_GUID")
);

DROP TABLE IF EXISTS RELATED_TAB_ROLES;
CREATE TABLE "RELATED_TAB_ROLES"
(
	"RELATED_TAB_ROLE_GUID" Varchar(36) NOT NULL,
	"ISVP" Varchar(100) NOT NULL,
	"ISVP_ROLE" Varchar(100) NOT NULL,
	"RELATED_TAB_GUID" Varchar(36) NOT NULL,
 PRIMARY KEY ("RELATED_TAB_ROLE_GUID")
);

DROP TABLE IF EXISTS RELATED_TABS;
CREATE TABLE "RELATED_TABS"
(
	"RELATED_TAB_GUID" Varchar(36) NOT NULL,
	"ORGANIZATION_NAME" Varchar(50) NOT NULL,
	"URL" Varchar(100) NOT NULL,
	"SEQUENCE" Integer NOT NULL,
	"TAB_DESCR" Varchar(50) NOT NULL,
	"TAB_URL" Varchar(100) NOT NULL,
 PRIMARY KEY ("RELATED_TAB_GUID")
);

DROP TABLE IF EXISTS CONFIG_PARAMS;
CREATE TABLE "CONFIG_PARAMS"
(
	"PARAMETER_GUID" Varchar(36) NOT NULL,
	"PARAMETER_NAME" Varchar(100) NOT NULL,
	"PARAMETER_TYPE" Smallint NOT NULL,
	"PARAMETER_VALUE" Varchar(255),
	"DESCR" Varchar(255),
	"DATE_MODIFIED" DateTime,
	"MODIFIED_BY_DN" Varchar(200) NOT NULL,
 PRIMARY KEY ("PARAMETER_GUID")
);


/* Create Alternate Keys */


/* Create Indexes */
CREATE UNIQUE INDEX "IX_ERRORS_INDEX" ON "ERRORS"  ("EXCEPTION_ID","SEQUENCE_NUMBER");
CREATE INDEX "IX_ERRORS_OBJECT" ON "ERRORS"  ("OBJECT_GUID","CREATION_DATE");
CREATE INDEX "IX_ERRORS_ACCOUNT" ON "ERRORS"  ("ORGANIZATION_CN","USER_CN","OBJECT_GUID","CREATION_DATE");
CREATE UNIQUE INDEX "IX_PARAMETERS" ON "PARAMETERS"  ("PARAMETER_NAME","ORGANIZATION_NAME");
CREATE INDEX "IX_RELATED_TAB_ROLES" ON "RELATED_TAB_ROLES"  ("ISVP");
CREATE UNIQUE INDEX "IX_RELATED_TABS" ON "RELATED_TABS"  ("ORGANIZATION_NAME","URL","SEQUENCE");
CREATE UNIQUE INDEX "IX_CONFIG_PARAMS" ON "CONFIG_PARAMS"  ("PARAMETER_NAME");


/* Create Foreign Keys */

ALTER TABLE "RELATED_TAB_ROLES" ADD Constraint "FK_RELATED_TABS_RELATED_TAB_ROLES" FOREIGN KEY ("RELATED_TAB_GUID") REFERENCES "RELATED_TABS" ("RELATED_TAB_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;





/* Create Tables */
DROP TABLE IF EXISTS ACTIVITIES;
CREATE TABLE "ACTIVITIES"
(
	"ACTIVITY_GUID" Varchar(36) NOT NULL,
	"MODEL_REVISION_GUID" Varchar(36) NOT NULL,
	"ACTIVITY_DESCR" Varchar(255) NOT NULL,
	"ACTIVITY_ACTION" Varchar(200) NOT NULL,
	"ACTIVITY_TYPE_GUID" Varchar(36) NOT NULL,
	"ACTIVITY_LOCATION" Smallint,
	"RUNNING_MODE" Smallint,
	"ACTIVITY_DATA" Varchar(255),
 PRIMARY KEY ("ACTIVITY_GUID")
);

DROP TABLE IF EXISTS ACTIVITY_TYPES;
CREATE TABLE "ACTIVITY_TYPES"
(
	"ACTIVITY_TYPE_GUID" Varchar(36) NOT NULL,
	"ACTIVITY_TYPE_NAME" Varchar(50),
 PRIMARY KEY ("ACTIVITY_TYPE_GUID")
);

DROP TABLE IF EXISTS BUSINESS_OBJECTS;
CREATE TABLE "BUSINESS_OBJECTS"
(
	"BUSINESS_OBJECT_GUID" Varchar(36) NOT NULL,
	"QUALIFIED_CLASS_NAME" Varchar(200) NOT NULL,
	"BUSINESS_OBJECT_NAME" Varchar(50) NOT NULL,
 PRIMARY KEY ("BUSINESS_OBJECT_GUID")
);

DROP TABLE IF EXISTS EVENTS;
CREATE TABLE "EVENTS"
(
	"EVENT_GUID" Varchar(36) NOT NULL,
	"TARGET_GUID" Varchar(36) NOT NULL,
	"SOURCE_GUID" Varchar(36),
	"TARGET_CLASS_NAME" Varchar(200) NOT NULL,
	"EVENT" Varchar(100) NOT NULL,
	"CREATION_DATE" DateTime NOT NULL,
	"CONTEXT_USER_CN" Varchar(50) NOT NULL,
	"ORGANIZATION_CN" Varchar(50) NOT NULL,
	"SOURCE_CLASS_NAME" Varchar(200),
 PRIMARY KEY ("EVENT_GUID")
);

DROP TABLE IF EXISTS GUARD_TYPES;
CREATE TABLE "GUARD_TYPES"
(
	"GUARD_TYPE_GUID" Varchar(36) NOT NULL,
	"GUARD_TYPE_NAME" Varchar(50),
 PRIMARY KEY ("GUARD_TYPE_GUID")
);

DROP TABLE IF EXISTS GUARDS;
CREATE TABLE "GUARDS"
(
	"GUARD_GUID" Varchar(36) NOT NULL,
	"MODEL_REVISION_GUID" Varchar(36) NOT NULL,
	"GUARD_NAME" Varchar(50),
	"EXPRESSION" Text,
	"GUARD_TYPE_GUID" Varchar(36) NOT NULL,
	"BUSINESS_OBJECT_GUID" Varchar(36),
 PRIMARY KEY ("GUARD_GUID")
);

DROP TABLE IF EXISTS MODEL_EVENTS;
CREATE TABLE "MODEL_EVENTS"
(
	"MODEL_EVENT_GUID" Varchar(36) NOT NULL,
	"MODEL_REVISION_GUID" Varchar(36) NOT NULL,
	"EVENT" Varchar(100) NOT NULL,
 PRIMARY KEY ("MODEL_EVENT_GUID")
);

DROP TABLE IF EXISTS MODEL_REVISIONS;
CREATE TABLE "MODEL_REVISIONS"
(
	"MODEL_REVISION_GUID" Varchar(36) NOT NULL,
	"MODEL_GUID" Varchar(36) NOT NULL,
	"REVISION" Integer NOT NULL,
	"START_STATE_GUID" Varchar(36),
	"MODEL_REVISION_DESCR" Text,
	"DATE_MODIFIED" DateTime,
	"MODIFIED_BY_DN" Varchar(200) NOT NULL,
 PRIMARY KEY ("MODEL_REVISION_GUID")
);

DROP TABLE IF EXISTS STATE_HISTORY;
CREATE TABLE "STATE_HISTORY"
(
	"STATE_HISTORY_GUID" Varchar(36) NOT NULL,
	"BUSINESS_OBJECT_GUID" Varchar(36) NOT NULL,
	"KEY_GUID" Varchar(36) NOT NULL,
	"LOG_DATE" DateTime NOT NULL,
	"STATE_GUID" Varchar(36),
	"TRANSITION_GUID" Varchar(36),
	"ORGANIZATION_GUID" Varchar(36),
 PRIMARY KEY ("STATE_HISTORY_GUID")
);

DROP TABLE IF EXISTS STATES;
CREATE TABLE "STATES"
(
	"STATE_GUID" Varchar(36) NOT NULL,
	"MODEL_REVISION_GUID" Varchar(36) NOT NULL,
	"STATE_ID" Integer NOT NULL,
	"STATE_NAME" Varchar(50),
	"ACTIVITY_GUID" Varchar(36),
 PRIMARY KEY ("STATE_GUID")
);

DROP TABLE IF EXISTS TICKETS;
CREATE TABLE "TICKETS"
(
	"TICKET_GUID" Varchar(36) NOT NULL,
	"ORDER_GUID" Varchar(36),
	"ORDER_LINE_GUID" Varchar(36),
	"LAST_MODIFICATION_DATE" DateTime NOT NULL,
	"STATUS" Integer NOT NULL,
	"QUALIFIED_CLASS_NAME" Varchar(200) NOT NULL,
	"BUSINESS_OBJECT_GUID" Varchar(36) NOT NULL,
	"POLLER_ID" Varchar(200),
	"ACTION" Integer NOT NULL,
	"CONTEXT_USER_CN" Varchar(50) NOT NULL,
	"ORGANIZATION_CN" Varchar(50) NOT NULL,
	"DEPENDS_ON_GUID" Varchar(36),
	"ACTIVITY_STATE_ID" Smallint,
	"CREATION_DATE" DateTime NOT NULL,
	"PROCESS_STATE_GUID" Varchar(36),
	"FUNCTIONAL_NAME" Varchar(200) NOT NULL,
	"CLUSTER_NAME" Varchar(50),
	"PROCESS_INSTANCE_ID" Varchar(50),
 PRIMARY KEY ("TICKET_GUID")
);

DROP TABLE IF EXISTS TRANSITIONS;
CREATE TABLE "TRANSITIONS"
(
	"TRANSITION_GUID" Varchar(36) NOT NULL,
	"MODEL_REVISION_GUID" Varchar(36) NOT NULL,
	"SOURCE_STATE_GUID" Varchar(36) NOT NULL,
	"TARGET_STATE_GUID" Varchar(36),
	"PRIORITY" Integer,
	"TRANSITION_NAME" Varchar(50),
	"GUARD_GUID" Varchar(36),
	"MODEL_EVENT_GUID" Varchar(36),
 PRIMARY KEY ("TRANSITION_GUID")
);

DROP TABLE IF EXISTS MODEL_SETS;
CREATE TABLE "MODEL_SETS"
(
	"MODEL_SET_GUID" Varchar(36) NOT NULL,
	"MODEL_SET_NAME" Varchar(50) NOT NULL,
	"MODEL_SET_DESCR" Text,
	"DATE_MODIFIED" DateTime,
	"MODIFIED_BY_DN" Varchar(200) NOT NULL,
 PRIMARY KEY ("MODEL_SET_GUID")
);

DROP TABLE IF EXISTS MODEL_SET_LINES;
CREATE TABLE "MODEL_SET_LINES"
(
	"MODEL_SET_LINE_GUID" Varchar(36) NOT NULL,
	"MODEL_GUID" Varchar(36) NOT NULL,
	"MODEL_SET_GUID" Varchar(36) NOT NULL,
	"BUSINESS_OBJECT_GUID" Varchar(36) NOT NULL,
	"DATE_MODIFIED" DateTime,
	"MODIFIED_BY_DN" Varchar(200) NOT NULL,
 PRIMARY KEY ("MODEL_SET_LINE_GUID","MODEL_SET_GUID")
);

DROP TABLE IF EXISTS METHOD_MODEL_SETS;
CREATE TABLE "METHOD_MODEL_SETS"
(
	"METHOD_MODEL_SET_GUID" Varchar(36) NOT NULL,
	"METHOD_GUID" Varchar(36) NOT NULL,
	"CLUSTER_GUID" Varchar(36),
	"ORGANIZATION_GUID" Varchar(36),
	"MODEL_SET_GUID" Varchar(36) NOT NULL,
	"METHOD_MODEL_SET_DESCR" Text,
	"DATE_MODIFIED" DateTime,
	"MODIFIED_BY_DN" Varchar(200) NOT NULL,
 PRIMARY KEY ("METHOD_MODEL_SET_GUID")
);

DROP TABLE IF EXISTS METHODS;
CREATE TABLE "METHODS"
(
	"METHOD_GUID" Varchar(36) NOT NULL,
	"METHOD_NAME" Varchar(128) NOT NULL,
	"METHOD_NAMESPACE" Varchar(128) NOT NULL,
	"METHOD_DESCR" Text,
	"DATE_MODIFIED" DateTime,
	"MODIFIED_BY_DN" Varchar(200) NOT NULL,
 PRIMARY KEY ("METHOD_GUID")
);

DROP TABLE IF EXISTS MODELS;
CREATE TABLE "MODELS"
(
	"MODEL_GUID" Varchar(36) NOT NULL,
	"BUSINESS_OBJECT_GUID" Varchar(36) NOT NULL,
	"MODEL_NAME" Varchar(50),
	"MODEL_DESCR" Text,
	"RUNTIME_REVISION" Integer,
	"DATE_MODIFIED" DateTime,
	"MODIFIED_BY_DN" Varchar(200) NOT NULL,
 PRIMARY KEY ("MODEL_GUID")
);


/* Create Alternate Keys */

Alter Table "ACTIVITY_TYPES" add Constraint "IX_ACTIVITY_TYPE" UNIQUE ("ACTIVITY_TYPE_NAME");


Alter Table "TRANSITIONS" add Constraint "IX_TRANSITION_LINES" UNIQUE ("SOURCE_STATE_GUID","TARGET_STATE_GUID","MODEL_REVISION_GUID","GUARD_GUID","MODEL_EVENT_GUID");


/* Create Indexes */
CREATE UNIQUE INDEX "IX_BUSINESS_OBJECTS" ON "BUSINESS_OBJECTS"  ("BUSINESS_OBJECT_NAME");
CREATE INDEX "IX_EVENTS_TARGET" ON "EVENTS"  ("TARGET_GUID","CREATION_DATE");
CREATE INDEX "IX_GUARD_TYPES" ON "GUARD_TYPES"  ("GUARD_TYPE_NAME");
CREATE INDEX "IX_GUARD_NAMES" ON "GUARDS"  ("MODEL_REVISION_GUID","GUARD_NAME");
CREATE INDEX "IX_EVENT_NAMES" ON "MODEL_EVENTS"  ("MODEL_REVISION_GUID","EVENT");
CREATE UNIQUE INDEX "IX_MODEL_REVISIONS" ON "MODEL_REVISIONS"  ("MODEL_GUID","REVISION");
CREATE INDEX "IX_STATE_HISTORY" ON "STATE_HISTORY"  ("LOG_DATE");
CREATE INDEX "IX_STATE_GUID" ON "STATE_HISTORY"  ("STATE_GUID");
CREATE INDEX "IX_KEY_GUID" ON "STATE_HISTORY"  ("KEY_GUID");
CREATE UNIQUE INDEX "IX_STATES" ON "STATES"  ("MODEL_REVISION_GUID","STATE_NAME");
CREATE INDEX "IX_TICKETS" ON "TICKETS"  ("STATUS","LAST_MODIFICATION_DATE");
CREATE INDEX "IX_TICKETS_POLLER" ON "TICKETS"  ("POLLER_ID");
CREATE INDEX "IX_TRANSITIONS" ON "TRANSITIONS"  ("SOURCE_STATE_GUID","PRIORITY","TARGET_STATE_GUID");
CREATE INDEX "IX_TRANSITION_NAMES" ON "TRANSITIONS"  ("MODEL_REVISION_GUID","SOURCE_STATE_GUID","TRANSITION_NAME");
CREATE UNIQUE INDEX "IX_MODEL_SETS" ON "MODEL_SETS"  ("MODEL_SET_NAME");
CREATE UNIQUE INDEX "IX_MODEL_LINE_SETS" ON "MODEL_SET_LINES"  ("MODEL_SET_GUID","BUSINESS_OBJECT_GUID");
CREATE UNIQUE INDEX "IX_METHOD_MODEL_SETS" ON "METHOD_MODEL_SETS"  ("METHOD_GUID","CLUSTER_GUID","ORGANIZATION_GUID");
CREATE UNIQUE INDEX "IX_METHODS" ON "METHODS"  ("METHOD_NAME","METHOD_NAMESPACE");
CREATE UNIQUE INDEX "IX_MODELS" ON "MODELS"  ("BUSINESS_OBJECT_GUID","MODEL_NAME");


/* Create Foreign Keys */

ALTER TABLE "STATES" ADD Constraint "FK_STATES_ACTIVITY_1" FOREIGN KEY ("ACTIVITY_GUID") REFERENCES "ACTIVITIES" ("ACTIVITY_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ACTIVITIES" ADD Constraint "FK_ACTIVITY_TYPE" FOREIGN KEY ("ACTIVITY_TYPE_GUID") REFERENCES "ACTIVITY_TYPES" ("ACTIVITY_TYPE_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "STATE_HISTORY" ADD Constraint "FK_STATE_HISTORY_BUSINESS_OBJECTS" FOREIGN KEY ("BUSINESS_OBJECT_GUID") REFERENCES "BUSINESS_OBJECTS" ("BUSINESS_OBJECT_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "TICKETS" ADD Constraint "FK_TICKETS_BUSINESS_OBJECTS" FOREIGN KEY ("BUSINESS_OBJECT_GUID") REFERENCES "BUSINESS_OBJECTS" ("BUSINESS_OBJECT_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "MODELS" ADD Constraint "FK_BUSINESS_OBJECT_MODELS" FOREIGN KEY ("BUSINESS_OBJECT_GUID") REFERENCES "BUSINESS_OBJECTS" ("BUSINESS_OBJECT_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "GUARDS" ADD Constraint "FK_GUARD_TYPE" FOREIGN KEY ("GUARD_TYPE_GUID") REFERENCES "GUARD_TYPES" ("GUARD_TYPE_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "TRANSITIONS" ADD Constraint "FK_DECISSION_LINES_RULE" FOREIGN KEY ("GUARD_GUID") REFERENCES "GUARDS" ("GUARD_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "TRANSITIONS" ADD Constraint "FK_TRANSITIONS_MODEL_EVENTS" FOREIGN KEY ("MODEL_EVENT_GUID") REFERENCES "MODEL_EVENTS" ("MODEL_EVENT_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ACTIVITIES" ADD Constraint "FK_ACTIVITIES_MODELS" FOREIGN KEY ("MODEL_REVISION_GUID") REFERENCES "MODEL_REVISIONS" ("MODEL_REVISION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "STATES" ADD Constraint "FK_STATES_MODEL_REFERENCE" FOREIGN KEY ("MODEL_REVISION_GUID") REFERENCES "MODEL_REVISIONS" ("MODEL_REVISION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "TRANSITIONS" ADD Constraint "FK_TRANSITIONS_MODELS" FOREIGN KEY ("MODEL_REVISION_GUID") REFERENCES "MODEL_REVISIONS" ("MODEL_REVISION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "MODEL_REVISIONS" ADD Constraint "FK_DEFAULT_START_STATE" FOREIGN KEY ("START_STATE_GUID") REFERENCES "STATES" ("STATE_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "TRANSITIONS" ADD Constraint "FK_FROM_STATE" FOREIGN KEY ("SOURCE_STATE_GUID") REFERENCES "STATES" ("STATE_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "TRANSITIONS" ADD Constraint "FK_NEXT_STATE" FOREIGN KEY ("TARGET_STATE_GUID") REFERENCES "STATES" ("STATE_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "MODEL_SET_LINES" ADD Constraint "FK_MODEL_SETS_MODEL_SET_LINES" FOREIGN KEY ("MODEL_SET_GUID") REFERENCES "MODEL_SETS" ("MODEL_SET_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "METHOD_MODEL_SETS" ADD Constraint "FK_MODEL_SETS_METHOD_MODEL_SETS" FOREIGN KEY ("MODEL_SET_GUID") REFERENCES "MODEL_SETS" ("MODEL_SET_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "METHOD_MODEL_SETS" ADD Constraint "FK_METHODS_METHOD_MODEL_SETS" FOREIGN KEY ("METHOD_GUID") REFERENCES "METHODS" ("METHOD_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "MODEL_REVISIONS" ADD Constraint "FK_MODELS_MODEL_REVISIONS" FOREIGN KEY ("MODEL_GUID") REFERENCES "MODELS" ("MODEL_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "MODEL_SET_LINES" ADD Constraint "FK_MODEL_SET_LINES_MODELS" FOREIGN KEY ("MODEL_GUID") REFERENCES "MODELS" ("MODEL_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;







/* Create Tables */
DROP TABLE IF EXISTS ADDRESSES;
CREATE TABLE "ADDRESSES"
(
	"ADDRESS_GUID" Varchar(36) NOT NULL,
	"BUSINESS_PARTNER_GUID" Varchar(36) NOT NULL,
	"ADDRESS_TYPE" Smallint NOT NULL,
	"ADDRESS" Varchar(200),
	"ZIPCODE" Varchar(50),
	"STATE" Varchar(50),
	"CITY" Varchar(50),
	"COUNTRY" Varchar(50),
 PRIMARY KEY ("ADDRESS_GUID")
);

DROP TABLE IF EXISTS APPLICATION_BPMS;
CREATE TABLE "APPLICATION_BPMS"
(
	"APPLICATION_BPM_GUID" Varchar(36) NOT NULL,
	"APPLICATION_GUID" Varchar(36) NOT NULL,
	"BPM_NAME" Varchar(50) NOT NULL,
	"BPM_ID" Varchar(255) NOT NULL,
	"BPM_TYPE" Smallint NOT NULL,
	"RUNNING_MODE" Smallint NOT NULL,
 PRIMARY KEY ("APPLICATION_BPM_GUID")
);

DROP TABLE IF EXISTS APPLICATION_ROLES;
CREATE TABLE "APPLICATION_ROLES"
(
	"APPLICATION_ROLE_GUID" Varchar(36) NOT NULL,
	"ISVP_NAME" Varchar(100),
	"ROLE_NAME" Varchar(50) NOT NULL,
	"ROLE_ID" Varchar(255) NOT NULL,
	"APPLICATION_GUID" Varchar(36) NOT NULL,
	"ROLE_TYPE" Integer NOT NULL,
	"ROLE_DESCRIPTION" Varchar(100),
	"ROLE_CATEGORY" Integer,
 PRIMARY KEY ("APPLICATION_ROLE_GUID")
);

DROP TABLE IF EXISTS APPLICATION_XFORMS;
CREATE TABLE "APPLICATION_XFORMS"
(
	"APPLICATION_XFORM_GUID" Varchar(36) NOT NULL,
	"APPLICATION_GUID" Varchar(36) NOT NULL,
	"XFORM_NAME" Varchar(50) NOT NULL,
	"XFORM_ID" Varchar(255) NOT NULL,
	"XFORM_MODEL" Varchar(255) NOT NULL,
	"XFORM_TYPE" Smallint NOT NULL,
 PRIMARY KEY ("APPLICATION_XFORM_GUID")
);

DROP TABLE IF EXISTS APPLICATIONS;
CREATE TABLE "APPLICATIONS"
(
	"APPLICATION_GUID" Varchar(36) NOT NULL,
	"ISV_GUID" Varchar(36) NOT NULL,
	"APPLICATION_NAME" Varchar(50) NOT NULL,
	"APPLICATION_AVAILABILITY" Integer NOT NULL,
	"ORGANIZATION_GUID" Varchar(36),
	"VERSION" Varchar(10),
	"OBJECT_STATE_ID" Smallint,
	"DESCR" Varchar(255),
	"APPLICATION_ID" Varchar(50) NOT NULL,
	"APPLICATION_TYPE" Integer NOT NULL,
 PRIMARY KEY ("APPLICATION_GUID")
);

DROP TABLE IF EXISTS AUTHENTICATED_USERS;
CREATE TABLE "AUTHENTICATED_USERS"
(
	"AUTHENTICATED_USER_GUID" Varchar(36) NOT NULL,
	"USER_PROFILE_GUID" Varchar(36) NOT NULL,
	"CLUSTER_GUID" Varchar(36) NOT NULL,
 PRIMARY KEY ("AUTHENTICATED_USER_GUID")
);

DROP TABLE IF EXISTS BUSINESS_PARTNERS;
CREATE TABLE "BUSINESS_PARTNERS"
(
	"BUSINESS_PARTNER_GUID" Varchar(36) NOT NULL,
	"BUSINESS_PARTNER_NAME" Varchar(50) NOT NULL,
	"LANGUAGE_CODE" Varchar(10) NOT NULL,
	"BUSINESS_PARTNER_CODE" Varchar(10),
	"BUSINESS_PARTNER_URL" Varchar(255),
	"COLLECTION_GUID" Varchar(36),
 PRIMARY KEY ("BUSINESS_PARTNER_GUID")
);

DROP TABLE IF EXISTS CLUSTERS;
CREATE TABLE "CLUSTERS"
(
	"CLUSTER_GUID" Varchar(36) NOT NULL,
	"CLUSTER_NAME" Varchar(50) NOT NULL,
	"CLUSTER_AVAILABILITY" Smallint NOT NULL,
	"CLUSTER_ACCESSIBILITY" Smallint NOT NULL,
	"CLUSTER_HEALTH" Smallint Default 0,
	"CORDYS_VERSION" Varchar(50),
	"INTERNAL_GATEWAY_URL" Varchar(150) NOT NULL,
	"INTERNAL_GATEWAY_PORT" Integer NOT NULL Default 80,
	"INTERNAL_GATEWAY_PROTOCOL" Smallint NOT NULL Default 0,
	"EXTERNAL_GATEWAY_URL" Varchar(150) NOT NULL,
	"EXTERNAL_GATEWAY_PORT" Integer NOT NULL Default 80,
	"EXTERNAL_GATEWAY_PROTOCOL" Smallint NOT NULL Default 0,
	"ADMIN_CLUSTER" Smallint NOT NULL,
	"OBJECT_STATE_ID" Smallint,
	"CLUSTER_TYPE" Smallint NOT NULL,
	"LDAP_ROOT" Varchar(150),
 PRIMARY KEY ("CLUSTER_GUID")
);

DROP TABLE IF EXISTS INSTALLED_APPLICATIONS;
CREATE TABLE "INSTALLED_APPLICATIONS"
(
	"INSTALLED_APPLICATION_GUID" Varchar(36) NOT NULL,
	"APPLICATION_GUID" Varchar(36) NOT NULL,
	"CLUSTER_GUID" Varchar(36) NOT NULL,
	"OBJECT_STATE_ID" Smallint,
	"CLUSTER_AVAILABILITY" Smallint NOT NULL,
 PRIMARY KEY ("INSTALLED_APPLICATION_GUID")
);

DROP TABLE IF EXISTS ORDER_LINES;
CREATE TABLE "ORDER_LINES"
(
	"ORDER_LINE_GUID" Varchar(36) NOT NULL,
	"ORDER_GUID" Varchar(36) NOT NULL,
	"LINE_NR" Integer NOT NULL,
	"OBJECT_GUID" Varchar(36),
	"BUSINESS_OBJECT_GUID" Varchar(36),
	"REASON_TEXT" Text,
	"DEPENDS_ON" Varchar(36),
	"ORDER_LINE_ACTION" Varchar(100),
	"READY_FLAG" Smallint,
	"QUALIFIED_CLASS_NAME" Varchar(200),
	"PROCESS_STATE_GUID" Varchar(36),
	"READY_FOR_APPROVAL" Smallint,
 PRIMARY KEY ("ORDER_LINE_GUID")
);

DROP TABLE IF EXISTS ORDER_TYPES;
CREATE TABLE "ORDER_TYPES"
(
	"ORDER_TYPE_GUID" Varchar(36) NOT NULL,
	"LANGUAGE_CODE" Char(10) NOT NULL,
	"ORDER_TYPE_DESCR" Varchar(100) NOT NULL,
 PRIMARY KEY ("ORDER_TYPE_GUID")
);

DROP TABLE IF EXISTS ORDERS;
CREATE TABLE "ORDERS"
(
	"ORDER_GUID" Varchar(36) NOT NULL,
	"CONTEXT_USER_CN" Varchar(50),
	"CONTEXT_ORGANIZATION_CN" Varchar(50),
	"REASON_TEXT" Text,
	"ORDER_ACTION" Varchar(100),
	"ORDER_TYPE_GUID" Varchar(36) NOT NULL,
	"SUMMARY" Varchar(255) NOT NULL,
	"CREATION_DATE" DateTime NOT NULL,
	"NOTIFY_USERS" Smallint,
	"EMAIL_TO" Text,
	"EMAIL_CC" Text,
	"EMAIL_BCC" Text,
	"MAIL_TRANSFORMATION" Varchar(256),
	"PROCESS_STATE_GUID" Varchar(36),
	"ORGANIZATION_GUID" Varchar(36),
 PRIMARY KEY ("ORDER_GUID")
);

DROP TABLE IF EXISTS ORG_APPL_SUBSCRIPTIONS;
CREATE TABLE "ORG_APPL_SUBSCRIPTIONS"
(
	"ORG_APPL_SUBSCRIPTION_GUID" Varchar(36) NOT NULL,
	"ORGANIZATION_GUID" Varchar(36) NOT NULL,
	"INSTALLED_APPLICATION_GUID" Varchar(36),
	"REGISTER_DATE" DateTime NOT NULL,
	"UNREGISTER_DATE" DateTime,
	"APPLICATION_CONTENT" Text,
	"APPLICATION_GUID" Varchar(36) NOT NULL,
	"OBJECT_STATE_ID" Smallint,
	"CHANNEL_GUID" Varchar(36),
 PRIMARY KEY ("ORG_APPL_SUBSCRIPTION_GUID")
);

DROP TABLE IF EXISTS ORGANIZATIONAL_USERS;
CREATE TABLE "ORGANIZATIONAL_USERS"
(
	"ORGANIZATIONAL_USER_GUID" Varchar(36) NOT NULL,
	"AUTHENTICATED_USER_GUID" Varchar(36) NOT NULL,
	"ORGANIZATION_GUID" Varchar(36) NOT NULL,
	"REGISTER_DATE" DateTime,
	"UNREGISTER_DATE" DateTime,
	"OBJECT_STATE_ID" Smallint NOT NULL,
 PRIMARY KEY ("ORGANIZATIONAL_USER_GUID")
);

DROP TABLE IF EXISTS ORGANIZATIONS;
CREATE TABLE "ORGANIZATIONS"
(
	"ORGANIZATION_GUID" Varchar(36) NOT NULL,
	"SUBDOMAIN_NAME" Varchar(100),
	"BUSINESS_PARTNER_GUID" Varchar(36) NOT NULL,
	"ORGANIZATION_NAME" Varchar(50) NOT NULL,
	"ORGANIZATION_FULL_NAME" Varchar(200),
	"LANGUAGE_CODE" Varchar(10),
	"REGISTER_DATE" DateTime,
	"UNREGISTER_DATE" DateTime,
	"CLUSTER_GUID" Varchar(36) NOT NULL,
	"OBJECT_STATE_ID" Smallint,
	"CHANNEL_GUID" Varchar(36) NOT NULL,
	"COLLECTION_GUID" Varchar(36),
 PRIMARY KEY ("ORGANIZATION_GUID")
);

DROP TABLE IF EXISTS USER_APPL_SUBSCRIPTIONS;
CREATE TABLE "USER_APPL_SUBSCRIPTIONS"
(
	"USER_APPL_SUBSCRIPTION_GUID" Varchar(36) NOT NULL,
	"ORGANIZATIONAL_USER_GUID" Varchar(36) NOT NULL,
	"ORG_APPL_SUBSCRIPTION_GUID" Varchar(36) NOT NULL,
	"SUBSCRIBE_DATE" DateTime,
	"APPLICATION_CONTENT" Text,
	"APPLICATION_GUID" Varchar(36) NOT NULL,
	"OBJECT_STATE_ID" Smallint NOT NULL,
	"USER_PROFILE_GUID" Varchar(36) NOT NULL,
 PRIMARY KEY ("USER_APPL_SUBSCRIPTION_GUID")
);

DROP TABLE IF EXISTS USER_APPLICATION_ROLES;
CREATE TABLE "USER_APPLICATION_ROLES"
(
	"USER_APPLICATION_ROLE_GUID" Varchar(36) NOT NULL,
	"USER_APPL_SUBSCRIPTION_GUID" Varchar(36) NOT NULL,
	"APPLICATION_ROLE_GUID" Varchar(36) NOT NULL,
	"OBJECT_STATE_ID" Smallint,
 PRIMARY KEY ("USER_APPLICATION_ROLE_GUID")
);

DROP TABLE IF EXISTS USER_PROFILES;
CREATE TABLE "USER_PROFILES"
(
	"USER_PROFILE_GUID" Varchar(36) NOT NULL,
	"USER_NAME" Varchar(255) NOT NULL,
	"PASSWORD" Varchar(100),
	"FIRST_NAME" Varchar(128),
	"MIDDLE_NAME" Varchar(66),
	"LAST_NAME" Varchar(128),
	"EMAIL" Varchar(255) NOT NULL,
	"LANGUAGE_CODE" Varchar(10) NOT NULL,
	"FULL_NAME" Varchar(255),
	"TITLE" Varchar(50),
	"DESCR" Varchar(250),
	"SUFFIX" Varchar(50),
	"EXTENSION_1" Varchar(100),
	"EXTENSION_2" Varchar(100),
	"OBJECT_STATE_ID" Smallint NOT NULL,
 PRIMARY KEY ("USER_PROFILE_GUID")
);

DROP TABLE IF EXISTS ARCH_USER_APPL_SUBSCRIPTIONS;
CREATE TABLE "ARCH_USER_APPL_SUBSCRIPTIONS"
(
	"USER_APPL_SUBSCRIPTION_GUID" Varchar(36) NOT NULL,
	"ORGANIZATIONAL_USER_GUID" Varchar(36) NOT NULL,
	"ORG_APPL_SUBSCRIPTION_GUID" Varchar(36) NOT NULL,
	"SUBSCRIBE_DATE" DateTime,
	"UNSUBSCRIBE_DATE" DateTime,
	"APPLICATION_CONTENT" Text,
	"APPLICATION_GUID" Varchar(36) NOT NULL,
	"OBJECT_STATE_ID" Smallint NOT NULL,
 PRIMARY KEY ("USER_APPL_SUBSCRIPTION_GUID")
);

DROP TABLE IF EXISTS APPLICATION_PROPERTIES;
CREATE TABLE "APPLICATION_PROPERTIES"
(
	"APPLICATION_PROPERTY_GUID" Varchar(36) NOT NULL,
	"APPLICATION_GUID" Varchar(36) NOT NULL,
	"NAMESPACE" Varchar(128) NOT NULL,
	"PROPERTY_NAME" Varchar(50) NOT NULL,
	"PROPERTY_TYPE" Smallint NOT NULL,
	"PROPERTY_VALUE" Text,
 PRIMARY KEY ("APPLICATION_PROPERTY_GUID")
);

DROP TABLE IF EXISTS ORGANIZATION_PROPERTIES;
CREATE TABLE "ORGANIZATION_PROPERTIES"
(
	"ORGANIZATION_PROPERTY_GUID" Varchar(36) NOT NULL,
	"ORGANIZATION_GUID" Varchar(36) NOT NULL,
	"NAMESPACE" Varchar(128) NOT NULL,
	"PROPERTY_NAME" Varchar(50) NOT NULL,
	"PROPERTY_TYPE" Smallint NOT NULL,
	"PROPERTY_VALUE" Text,
 PRIMARY KEY ("ORGANIZATION_PROPERTY_GUID")
);

DROP TABLE IF EXISTS CHANNELS;
CREATE TABLE "CHANNELS"
(
	"CHANNEL_GUID" Varchar(36) NOT NULL,
	"BUSINESS_PARTNER_GUID" Varchar(36) NOT NULL,
	"CHANNEL_NAME" Varchar(50) NOT NULL,
	"CHANNEL_DESCR" Text,
	"NAMESPACE" Varchar(128) NOT NULL,
	"ORGANIZATION_GUID" Varchar(36),
	"COLLECTION_GUID" Varchar(36),
	"CHANNEL_CURRENCY_CODE" Char(3),
	"DOMAIN_NAME" Varchar(255),
	"DOMAIN_ACTION" Varchar(255),
	"CHANNEL_CLUSTER_GUID" Varchar(36),
	"COLLECTION_VISIBILITY" Integer NOT NULL,
 PRIMARY KEY ("CHANNEL_GUID")
);

DROP TABLE IF EXISTS COLLECTIONS;
CREATE TABLE "COLLECTIONS"
(
	"COLLECTION_GUID" Varchar(36) NOT NULL,
	"ROOT_COLLECTION_GUID" Varchar(36) NOT NULL,
	"COLLECTION_NAME" Varchar(50),
	"OWNER_OBJECT_GUID" Varchar(36) NOT NULL,
	"OWNER_OBJECT_TYPE" Integer NOT NULL,
	"CREATION_DATE" DateTime,
	"MODIFICATION_DATE" DateTime,
	"PUBLICATION_DATE" DateTime,
 PRIMARY KEY ("COLLECTION_GUID")
);

DROP TABLE IF EXISTS APPLICATION_COLLECTION_ITEMS;
CREATE TABLE "APPLICATION_COLLECTION_ITEMS"
(
	"COLLECTION_ITEM_GUID" Varchar(36) NOT NULL,
	"APPLICATION_GUID" Varchar(36) NOT NULL,
	"COLLECTION_PRICE" Double precision,
	"FULL_APPL_DESCR" Text,
	"COLLECTION_TAGS" Varchar(255),
	"THUMBNAIL_URL" Varchar(255),
	"CURRENCY_CODE" Char(3) NOT NULL,
	"PRICE_MODEL_GUID" Varchar(36) NOT NULL,
	"PROVIDER_NAME" Varchar(50) NOT NULL,
 PRIMARY KEY ("COLLECTION_ITEM_GUID")
);

DROP TABLE IF EXISTS ORG_DEPLOYED_APPLICATIONS;
CREATE TABLE "ORG_DEPLOYED_APPLICATIONS"
(
	"ORG_DEPLOYED_APPLICATION_GUID" Varchar(36) NOT NULL,
	"APPLICATION_GUID" Varchar(36) NOT NULL,
	"ORGANIZATION_GUID" Varchar(36) NOT NULL,
	"OBJECT_STATE_ID" Smallint,
	"INSTALLED_APPLICATION_GUID" Varchar(36),
 PRIMARY KEY ("ORG_DEPLOYED_APPLICATION_GUID")
);

DROP TABLE IF EXISTS COLLECTION_ITEM_PROPERTIES;
CREATE TABLE "COLLECTION_ITEM_PROPERTIES"
(
	"COLLECTION_ITEM_PROPERTY_GUID" Varchar(36) NOT NULL,
	"COLLECTION_ITEM_GUID" Varchar(36) NOT NULL,
	"NAMESPACE" Varchar(128) NOT NULL,
	"PROPERTY_NAME" Varchar(50) NOT NULL,
	"PROPERTY_TYPE" Smallint NOT NULL,
	"PROPERTY_VALUE" Text,
 PRIMARY KEY ("COLLECTION_ITEM_PROPERTY_GUID")
);

DROP TABLE IF EXISTS COLLECTION_PROPERTIES;
CREATE TABLE "COLLECTION_PROPERTIES"
(
	"COLLECTION_PROPERTY_GUID" Varchar(36) NOT NULL,
	"COLLECTION_GUID" Varchar(36) NOT NULL,
	"NAMESPACE" Varchar(128) NOT NULL,
	"PROPERTY_NAME" Varchar(50) NOT NULL,
	"PROPERTY_TYPE" Smallint NOT NULL,
	"PROPERTY_VALUE" Text,
 PRIMARY KEY ("COLLECTION_PROPERTY_GUID")
);

DROP TABLE IF EXISTS ROLE_AUTHORIZATIONS;
CREATE TABLE "ROLE_AUTHORIZATIONS"
(
	"ROLE_AUTHORIZATION_GUID" Varchar(36) NOT NULL,
	"APPLICATION_ROLE_GUID" Varchar(36) NOT NULL,
	"MIN_AUTHENTICATION_LEVEL" Integer NOT NULL,
	"COLLECTION_ITEM_GUID" Varchar(36) NOT NULL,
 PRIMARY KEY ("ROLE_AUTHORIZATION_GUID")
);

DROP TABLE IF EXISTS COLLECTION_ITEMS;
CREATE TABLE "COLLECTION_ITEMS"
(
	"COLLECTION_ITEM_GUID" Varchar(36) NOT NULL,
	"COLLECTION_GUID" Varchar(36) NOT NULL,
	"ROOT_COLLECTION_GUID" Varchar(36),
	"COLLECTION_ITEM_NAME" Varchar(50) NOT NULL,
	"MIN_VISIBILITY_LEVEL" Integer NOT NULL,
	"MIN_AUTHORIZATION_LEVEL" Integer NOT NULL,
	"ITEM_DESCR" Text,
	"COLLECTION_ITEM_TYPE" Integer NOT NULL,
	"ITEM_SEQUENCE" Integer,
	"CREATION_DATE" DateTime,
	"MODIFICATION_DATE" DateTime,
	"PUBLICATION_DATE" DateTime,
 PRIMARY KEY ("COLLECTION_ITEM_GUID")
);

DROP TABLE IF EXISTS SUB_COLLECTION_ITEMS;
CREATE TABLE "SUB_COLLECTION_ITEMS"
(
	"COLLECTION_ITEM_GUID" Varchar(36) NOT NULL,
	"SUB_COLLECTION_GUID" Varchar(36) NOT NULL,
 PRIMARY KEY ("COLLECTION_ITEM_GUID")
);

DROP TABLE IF EXISTS COLLECTION_ITEM_REQUESTS;
CREATE TABLE "COLLECTION_ITEM_REQUESTS"
(
	"COLLECTION_ITEM_GUID" Varchar(36) NOT NULL,
	"APPLICATION_GUID" Varchar(36) NOT NULL,
	"COLLECTION_PRICE" Double precision,
	"FULL_APPL_DESCR" Text,
	"COLLECTION_TAGS" Varchar(255),
	"THUMBNAIL_URL" Varchar(255),
	"ISVP_URL" Varchar(255),
	"OBJECT_STATE_ID" Smallint,
	"CURRENCY_CODE" Char(3) NOT NULL,
	"PRICE_MODEL_GUID" Varchar(36) NOT NULL,
	"ORGANIZATION_NAME" Varchar(50),
	"USER_NAME" Varchar(50),
	"REQUEST_EVAL_TEXT" Text,
	"TEST_ORGANIZATION_NAME" Varchar(50),
	"PROVIDER_NAME" Varchar(50) NOT NULL,
 PRIMARY KEY ("COLLECTION_ITEM_GUID")
);

DROP TABLE IF EXISTS CHANNEL_CLUSTERS;
CREATE TABLE "CHANNEL_CLUSTERS"
(
	"CHANNEL_CLUSTER_GUID" Varchar(36) NOT NULL,
	"CHANNEL_GUID" Varchar(36) NOT NULL,
	"CLUSTER_GUID" Varchar(36) NOT NULL,
	"DESCR" Varchar(255),
 PRIMARY KEY ("CHANNEL_CLUSTER_GUID")
);

DROP TABLE IF EXISTS CURRENCIES;
CREATE TABLE "CURRENCIES"
(
	"CURRENCY_CODE" Char(3) NOT NULL,
	"CURRENCY_DESCR" Varchar(50) NOT NULL,
 PRIMARY KEY ("CURRENCY_CODE")
);

DROP TABLE IF EXISTS PRICE_MODELS;
CREATE TABLE "PRICE_MODELS"
(
	"PRICE_MODEL_GUID" Varchar(36) NOT NULL,
	"PRICE_MODEL_NAME" Varchar(50),
	"MODEL_DESCR" Varchar(50),
 PRIMARY KEY ("PRICE_MODEL_GUID")
);

DROP TABLE IF EXISTS ORDER_WORKFLOWS;
CREATE TABLE "ORDER_WORKFLOWS"
(
	"ORDER_WORKFLOW_GUID" Varchar(36) NOT NULL,
	"ORDER_GUID" Varchar(36),
	"ORGANIZATION_GUID" Varchar(36),
 PRIMARY KEY ("ORDER_WORKFLOW_GUID")
);

DROP TABLE IF EXISTS ENTITY_SPECIFICATION;
CREATE TABLE "ENTITY_SPECIFICATION"
(
	"ENTITY_SPEC_GUID" Varchar(36) NOT NULL,
	"SPECIFICATION_NAME" Varchar(50) NOT NULL,
	"ENTITY_TYPE" Integer NOT NULL,
 PRIMARY KEY ("ENTITY_SPEC_GUID")
);

DROP TABLE IF EXISTS ENTITY_SPEC_CHARACTERISTICS;
CREATE TABLE "ENTITY_SPEC_CHARACTERISTICS"
(
	"ENTITY_SPEC_CHAR_GUID" Varchar(36) NOT NULL,
	"ENTITY_SPEC_GUID" Varchar(36) NOT NULL,
	"CHAR_SEQUENCE" Integer,
	"NAMESPACE" Varchar(128) NOT NULL,
	"NAME" Varchar(50) NOT NULL,
	"TYPE" Integer NOT NULL,
	"SINGLE_VALUED" Integer NOT NULL,
	"MAX_VALUE" Text,
	"MIN_VALUE" Text,
	"CHAR_VALUE" Text,
	"MIN_VISIBILITY_LEVEL" Integer NOT NULL,
	"MIN_AUTHORIZATION_LEVEL" Integer NOT NULL,
	"VALUE_REQUIRED" Integer NOT NULL,
	"CHAR_DESCR" Text,
 PRIMARY KEY ("ENTITY_SPEC_CHAR_GUID")
);

DROP TABLE IF EXISTS ENTITY_SPEC_CHAR_ENUMS;
CREATE TABLE "ENTITY_SPEC_CHAR_ENUMS"
(
	"ENTITY_SPEC_CHAR_ENUM_GUID" Varchar(36) NOT NULL,
	"ENTITY_SPEC_CHAR_GUID" Varchar(36) NOT NULL,
	"ENUM_ID" Integer NOT NULL,
	"ENUM_VALUE" Varchar(255) NOT NULL,
	"ENUM_SEQUENCE" Integer,
 PRIMARY KEY ("ENTITY_SPEC_CHAR_ENUM_GUID")
);

DROP TABLE IF EXISTS ORG_USER_CHAR_VALUES;
CREATE TABLE "ORG_USER_CHAR_VALUES"
(
	"ORG_USER_CHAR_VALUE_GUID" Varchar(36) NOT NULL,
	"ENTITY_SPEC_CHAR_GUID" Varchar(36) NOT NULL,
	"ORGANIZATIONAL_USER_GUID" Varchar(36) NOT NULL,
	"ORG_USER_CHAR_VALUE" Text,
 PRIMARY KEY ("ORG_USER_CHAR_VALUE_GUID")
);

DROP TABLE IF EXISTS ORGANIZATION_CHAR_VALUES;
CREATE TABLE "ORGANIZATION_CHAR_VALUES"
(
	"ORG_CHAR_VALUE_GUID" Varchar(36) NOT NULL,
	"ENTITY_SPEC_CHAR_GUID" Varchar(36) NOT NULL,
	"ORGANIZATION_GUID" Varchar(36) NOT NULL,
	"ORG_CHAR_VALUE" Text,
 PRIMARY KEY ("ORG_CHAR_VALUE_GUID")
);


/* Create Alternate Keys */


/* Create Indexes */
CREATE UNIQUE INDEX "IX_ADDRESSES" ON "ADDRESSES"  ("BUSINESS_PARTNER_GUID","ADDRESS_TYPE");
CREATE UNIQUE INDEX "IX_APPLICATION_BPMS" ON "APPLICATION_BPMS"  ("APPLICATION_GUID","BPM_TYPE");
CREATE UNIQUE INDEX "IX_APPLICATION_ROLES" ON "APPLICATION_ROLES"  ("APPLICATION_GUID","ROLE_NAME");
CREATE UNIQUE INDEX "IX_APPLICATION_XFORMS" ON "APPLICATION_XFORMS"  ("APPLICATION_GUID","XFORM_TYPE");
CREATE UNIQUE INDEX "IX_APPLICATIONS" ON "APPLICATIONS"  ("ISV_GUID","APPLICATION_NAME","VERSION");
CREATE UNIQUE INDEX "IX_APPLICATIONS_BY_ID" ON "APPLICATIONS"  ("APPLICATION_ID");
CREATE UNIQUE INDEX "IX_BUSINESS_PARTNERS" ON "BUSINESS_PARTNERS"  ("BUSINESS_PARTNER_NAME");
CREATE INDEX "IX_CLUSTERS_IS_ADMIN_CLUSTER" ON "CLUSTERS"  ("ADMIN_CLUSTER");
CREATE UNIQUE INDEX "IX_CLUSTER_NAME" ON "CLUSTERS"  ("CLUSTER_NAME");
CREATE UNIQUE INDEX "IX_INSTALLED_APPLICATIONS" ON "INSTALLED_APPLICATIONS"  ("APPLICATION_GUID","CLUSTER_GUID");
CREATE INDEX "IX_AVAILABLE_APPLICATIONS" ON "INSTALLED_APPLICATIONS"  ("APPLICATION_GUID","CLUSTER_AVAILABILITY");
CREATE INDEX "IX_ORDER_LINE_OBJECT" ON "ORDER_LINES"  ("OBJECT_GUID");
CREATE INDEX "IX_ORDER_TYPES" ON "ORDER_TYPES"  ("LANGUAGE_CODE");
CREATE INDEX "IX_ORDERS_ORDER_TYPE" ON "ORDERS"  ("ORDER_TYPE_GUID");
CREATE UNIQUE INDEX "IX_ORG_APPL_SUBSCRIPTIONS" ON "ORG_APPL_SUBSCRIPTIONS"  ("ORGANIZATION_GUID","APPLICATION_GUID");
CREATE INDEX "IX_CHANNEL_SUBSCRIPTIONS" ON "ORG_APPL_SUBSCRIPTIONS"  ("CHANNEL_GUID","APPLICATION_GUID");
CREATE UNIQUE INDEX "IX_ORGANIZATIONAL_USERS" ON "ORGANIZATIONAL_USERS"  ("AUTHENTICATED_USER_GUID","ORGANIZATION_GUID");
CREATE UNIQUE INDEX "IX_ORGANIZATIONS_NAME" ON "ORGANIZATIONS"  ("ORGANIZATION_NAME");
CREATE UNIQUE INDEX "IX_ORGANIZATIONS_OF_BUSINESSPARTNER" ON "ORGANIZATIONS"  ("BUSINESS_PARTNER_GUID","ORGANIZATION_GUID");
CREATE UNIQUE INDEX "IX_ORGANIZATIONS_SUBDOMAIN" ON "ORGANIZATIONS"  ("SUBDOMAIN_NAME");
CREATE UNIQUE INDEX "IX_USER_APPL_SUBSCRIPTION" ON "USER_APPL_SUBSCRIPTIONS"  ("ORGANIZATIONAL_USER_GUID","ORG_APPL_SUBSCRIPTION_GUID");
CREATE UNIQUE INDEX "IX_USER_APPLICATION_ROLES" ON "USER_APPLICATION_ROLES"  ("USER_APPL_SUBSCRIPTION_GUID","APPLICATION_ROLE_GUID");
CREATE UNIQUE INDEX "IX_USERS" ON "USER_PROFILES"  ("USER_NAME");
CREATE INDEX "IX_AR_USER_APPL_SUBSCRIPTION" ON "ARCH_USER_APPL_SUBSCRIPTIONS"  ("ORGANIZATIONAL_USER_GUID","ORG_APPL_SUBSCRIPTION_GUID");
CREATE INDEX "IX_AR_SUBSCRIPTION_DATE" ON "ARCH_USER_APPL_SUBSCRIPTIONS"  ("SUBSCRIBE_DATE","ORGANIZATIONAL_USER_GUID","USER_APPL_SUBSCRIPTION_GUID");
CREATE INDEX "IX_AR_UNSUBSCRIBE_DATE" ON "ARCH_USER_APPL_SUBSCRIPTIONS"  ("UNSUBSCRIBE_DATE","ORGANIZATIONAL_USER_GUID","USER_APPL_SUBSCRIPTION_GUID");
CREATE UNIQUE INDEX "IX_APPLICATION_PROPERTY" ON "APPLICATION_PROPERTIES"  ("APPLICATION_GUID","NAMESPACE","PROPERTY_NAME");
CREATE UNIQUE INDEX "IX_ORGANIZATION_PROPERTY" ON "ORGANIZATION_PROPERTIES"  ("ORGANIZATION_GUID","NAMESPACE","PROPERTY_NAME");
CREATE UNIQUE INDEX "IX_CHANNEL_NAME" ON "CHANNELS"  ("CHANNEL_NAME");
CREATE UNIQUE INDEX "IX_CHANNEL_NAMESPACE" ON "CHANNELS"  ("NAMESPACE");
CREATE INDEX "IX_CHANNEL_ADMIN_OFFICE" ON "CHANNELS"  ("ORGANIZATION_GUID");
CREATE INDEX "IX_CHANNEL_COLL_VISIBILITY" ON "CHANNELS"  ("COLLECTION_VISIBILITY");
CREATE INDEX "IX_ROOT_COLLECTIONS" ON "COLLECTIONS"  ("ROOT_COLLECTION_GUID","COLLECTION_GUID");
CREATE INDEX "IX_APPLICATION_COLLECTION_ITEM" ON "APPLICATION_COLLECTION_ITEMS"  ("COLLECTION_ITEM_GUID","APPLICATION_GUID");
CREATE INDEX "IX_APPLICATIONS_OF_COLLECTION_ITEM" ON "APPLICATION_COLLECTION_ITEMS"  ("APPLICATION_GUID","COLLECTION_ITEM_GUID");
CREATE UNIQUE INDEX "IX_COLLECTION_ITEM_PROPERTY" ON "COLLECTION_ITEM_PROPERTIES"  ("COLLECTION_ITEM_GUID","NAMESPACE","PROPERTY_NAME");
CREATE UNIQUE INDEX "IX_COLLECTION_PROPERTY" ON "COLLECTION_PROPERTIES"  ("COLLECTION_GUID","NAMESPACE","PROPERTY_NAME");
CREATE INDEX "IX_COLLECTION_ITEM_BY_TYPE" ON "COLLECTION_ITEMS"  ("COLLECTION_GUID","COLLECTION_ITEM_TYPE","ITEM_SEQUENCE","COLLECTION_ITEM_GUID");
CREATE INDEX "IX_ROOT_COLLECTION_ITEM_BY_TYPE" ON "COLLECTION_ITEMS"  ("ROOT_COLLECTION_GUID","COLLECTION_ITEM_TYPE","COLLECTION_ITEM_GUID");
CREATE INDEX "IX_VISIBLE_COLLECTION_ITEM_BY_TYPE" ON "COLLECTION_ITEMS"  ("COLLECTION_GUID","COLLECTION_ITEM_TYPE","MIN_VISIBILITY_LEVEL","COLLECTION_ITEM_GUID");
CREATE INDEX "IX_AUTHORIZED_COLLECTION_ITEMS_BY_TYPE" ON "COLLECTION_ITEMS"  ("COLLECTION_GUID","COLLECTION_ITEM_TYPE","MIN_AUTHORIZATION_LEVEL","COLLECTION_ITEM_GUID");
CREATE INDEX "IX_VISIBLE_ROOT_COLLECTION_ITEMS_BY_TYPE" ON "COLLECTION_ITEMS"  ("ROOT_COLLECTION_GUID","COLLECTION_ITEM_TYPE","MIN_VISIBILITY_LEVEL","COLLECTION_ITEM_GUID");
CREATE INDEX "IX_AUTHORIZED_ROOT_COLLECTION_ITEMS_BY_TYPE" ON "COLLECTION_ITEMS"  ("ROOT_COLLECTION_GUID","COLLECTION_ITEM_TYPE","MIN_AUTHORIZATION_LEVEL","COLLECTION_ITEM_GUID");
CREATE INDEX "IX_COLLECTION_ITEM_REQUESTS" ON "COLLECTION_ITEM_REQUESTS"  ("ORGANIZATION_NAME","COLLECTION_ITEM_GUID");
CREATE UNIQUE INDEX "IX_CHANNEL_CLUSTER" ON "CHANNEL_CLUSTERS"  ("CHANNEL_GUID","CLUSTER_GUID");
CREATE UNIQUE INDEX "IX_CLUSTER_CHANNEL" ON "CHANNEL_CLUSTERS"  ("CLUSTER_GUID","CHANNEL_GUID");
CREATE INDEX "IX_PRICE_MODELS" ON "PRICE_MODELS"  ("PRICE_MODEL_NAME");
CREATE INDEX "IX_ENT_SPEC_CHAR_SEQ" ON "ENTITY_SPEC_CHARACTERISTICS"  ("ENTITY_SPEC_GUID","CHAR_SEQUENCE");
CREATE UNIQUE INDEX "IX_ENT_SPEC_CHAR_NAME" ON "ENTITY_SPEC_CHARACTERISTICS"  ("ENTITY_SPEC_GUID","NAMESPACE","NAME");
CREATE INDEX "IX_ENT_SPEC_CHAR_ENUMS_SEQ" ON "ENTITY_SPEC_CHAR_ENUMS"  ("ENTITY_SPEC_CHAR_GUID","ENUM_SEQUENCE");
CREATE UNIQUE INDEX "ENTITY_SPEC_CHAR_ENUM_ID" ON "ENTITY_SPEC_CHAR_ENUMS"  ("ENTITY_SPEC_CHAR_GUID","ENUM_ID");
CREATE UNIQUE INDEX "IX_ORG_USER_CHAR_VALUE" ON "ORG_USER_CHAR_VALUES"  ("ORGANIZATIONAL_USER_GUID","ENTITY_SPEC_CHAR_GUID");
CREATE UNIQUE INDEX "IX_ORG_CHAR_VALUE" ON "ORGANIZATION_CHAR_VALUES"  ("ORGANIZATION_GUID","ENTITY_SPEC_CHAR_GUID");


/* Create Foreign Keys */

ALTER TABLE "USER_APPLICATION_ROLES" ADD Constraint "FK_USER_APPLICATION_ROLES_APPLICATION_ROLES" FOREIGN KEY ("APPLICATION_ROLE_GUID") REFERENCES "APPLICATION_ROLES" ("APPLICATION_ROLE_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ROLE_AUTHORIZATIONS" ADD Constraint "FK_APPLICATION_ROLES_ROLE_AUTHORIZATIONS" FOREIGN KEY ("APPLICATION_ROLE_GUID") REFERENCES "APPLICATION_ROLES" ("APPLICATION_ROLE_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "APPLICATION_BPMS" ADD Constraint "FK_APPLICATION_BPMS_APPLICATIONS" FOREIGN KEY ("APPLICATION_GUID") REFERENCES "APPLICATIONS" ("APPLICATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "APPLICATION_ROLES" ADD Constraint "FK_APPLICATION_ROLES_APPLICATIONS" FOREIGN KEY ("APPLICATION_GUID") REFERENCES "APPLICATIONS" ("APPLICATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "APPLICATION_XFORMS" ADD Constraint "FK_APPLICATION_XFORMS_APPLICATIONS" FOREIGN KEY ("APPLICATION_GUID") REFERENCES "APPLICATIONS" ("APPLICATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "INSTALLED_APPLICATIONS" ADD Constraint "FK_INSTALLED_APPLICATIONS_APPLICATIONS" FOREIGN KEY ("APPLICATION_GUID") REFERENCES "APPLICATIONS" ("APPLICATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORG_APPL_SUBSCRIPTIONS" ADD Constraint "FK_ORG_APPL_SUBSCRIPTIONS_APPLICATIONS" FOREIGN KEY ("APPLICATION_GUID") REFERENCES "APPLICATIONS" ("APPLICATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "USER_APPL_SUBSCRIPTIONS" ADD Constraint "FK_USER_APPL_SUBSCRIPTIONS_APPLICATIONS" FOREIGN KEY ("APPLICATION_GUID") REFERENCES "APPLICATIONS" ("APPLICATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "APPLICATION_PROPERTIES" ADD Constraint "FK_APPLICATIONS_APPLICATION_PROPERTIES" FOREIGN KEY ("APPLICATION_GUID") REFERENCES "APPLICATIONS" ("APPLICATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "APPLICATION_COLLECTION_ITEMS" ADD Constraint "FK_APPLICATIONS_COLLECTION_ITEMS" FOREIGN KEY ("APPLICATION_GUID") REFERENCES "APPLICATIONS" ("APPLICATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORG_DEPLOYED_APPLICATIONS" ADD Constraint "FK_APPLICATIONS_ORG_DEPLOYED_APPLICATIONS" FOREIGN KEY ("APPLICATION_GUID") REFERENCES "APPLICATIONS" ("APPLICATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORGANIZATIONAL_USERS" ADD Constraint "FK_UCF_ORGANIZATIONAL_USER_UCF_AUTHENTICATED_USER" FOREIGN KEY ("AUTHENTICATED_USER_GUID") REFERENCES "AUTHENTICATED_USERS" ("AUTHENTICATED_USER_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORGANIZATIONS" ADD Constraint "FK_ORGANIZATIONS_BUSINESS_PARTNERS" FOREIGN KEY ("BUSINESS_PARTNER_GUID") REFERENCES "BUSINESS_PARTNERS" ("BUSINESS_PARTNER_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "APPLICATIONS" ADD Constraint "FK_APPLICATIONS_BUSINESS_PARTNERS" FOREIGN KEY ("ISV_GUID") REFERENCES "BUSINESS_PARTNERS" ("BUSINESS_PARTNER_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ADDRESSES" ADD Constraint "FK_ADDRESS_BUSINESS_PARTNER" FOREIGN KEY ("BUSINESS_PARTNER_GUID") REFERENCES "BUSINESS_PARTNERS" ("BUSINESS_PARTNER_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "CHANNELS" ADD Constraint "FK_CHANNELS_BUSINESS_PARTNERS" FOREIGN KEY ("BUSINESS_PARTNER_GUID") REFERENCES "BUSINESS_PARTNERS" ("BUSINESS_PARTNER_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "AUTHENTICATED_USERS" ADD Constraint "FK_UCF_AUTHENTICATED_USER_CLUSTERS" FOREIGN KEY ("CLUSTER_GUID") REFERENCES "CLUSTERS" ("CLUSTER_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "INSTALLED_APPLICATIONS" ADD Constraint "FK_INSTALLED_APPLICATIONS_CLUSTERS" FOREIGN KEY ("CLUSTER_GUID") REFERENCES "CLUSTERS" ("CLUSTER_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORGANIZATIONS" ADD Constraint "FK_ORGANIZATIONS_CLUSTERS" FOREIGN KEY ("CLUSTER_GUID") REFERENCES "CLUSTERS" ("CLUSTER_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "CHANNEL_CLUSTERS" ADD Constraint "FK_CLUSTERS_CHANEL_CLUSTERS" FOREIGN KEY ("CLUSTER_GUID") REFERENCES "CLUSTERS" ("CLUSTER_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORG_APPL_SUBSCRIPTIONS" ADD Constraint "FK_ORG_APPL_SUBSCRIPTIONS_INSTALLED_APPLICATIONS" FOREIGN KEY ("INSTALLED_APPLICATION_GUID") REFERENCES "INSTALLED_APPLICATIONS" ("INSTALLED_APPLICATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORG_DEPLOYED_APPLICATIONS" ADD Constraint "FK_INSTALLED_APPLS_ORG_DEPLOYED_APPLS" FOREIGN KEY ("INSTALLED_APPLICATION_GUID") REFERENCES "INSTALLED_APPLICATIONS" ("INSTALLED_APPLICATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORDERS" ADD Constraint "FK_ORDERS_ORDER_TYPES" FOREIGN KEY ("ORDER_TYPE_GUID") REFERENCES "ORDER_TYPES" ("ORDER_TYPE_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORDER_LINES" ADD Constraint "FK_ORDER_LINES_ORDERS" FOREIGN KEY ("ORDER_GUID") REFERENCES "ORDERS" ("ORDER_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "USER_APPL_SUBSCRIPTIONS" ADD Constraint "FK_USER_APPL_SUBSCRIPTION_ORG_APPL_SUBSCRIPTIONS" FOREIGN KEY ("ORG_APPL_SUBSCRIPTION_GUID") REFERENCES "ORG_APPL_SUBSCRIPTIONS" ("ORG_APPL_SUBSCRIPTION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "USER_APPL_SUBSCRIPTIONS" ADD Constraint "FK_USER_SUBSCRIPTION_LINES_USERS" FOREIGN KEY ("ORGANIZATIONAL_USER_GUID") REFERENCES "ORGANIZATIONAL_USERS" ("ORGANIZATIONAL_USER_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORG_USER_CHAR_VALUES" ADD Constraint "FK_ORG_USERS_ORG_USER_CHAR_VALUES" FOREIGN KEY ("ORGANIZATIONAL_USER_GUID") REFERENCES "ORGANIZATIONAL_USERS" ("ORGANIZATIONAL_USER_GUID") ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE "ORG_APPL_SUBSCRIPTIONS" ADD Constraint "FK_REGISTRATION_LINES_REGISTRATIONS" FOREIGN KEY ("ORGANIZATION_GUID") REFERENCES "ORGANIZATIONS" ("ORGANIZATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORGANIZATIONAL_USERS" ADD Constraint "FK_UCF_ORGANIZATIONAL_USER_ORGANIZATIONS" FOREIGN KEY ("ORGANIZATION_GUID") REFERENCES "ORGANIZATIONS" ("ORGANIZATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORGANIZATION_PROPERTIES" ADD Constraint "FK_ORGANIZATION_ORGANIZATION_PROPERTIES" FOREIGN KEY ("ORGANIZATION_GUID") REFERENCES "ORGANIZATIONS" ("ORGANIZATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORDERS" ADD Constraint "FK_ORDERS_ORGANIZATIONS" FOREIGN KEY ("ORGANIZATION_GUID") REFERENCES "ORGANIZATIONS" ("ORGANIZATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORG_DEPLOYED_APPLICATIONS" ADD Constraint "FK_ORG_DEPLOYED_APPLICATIONS_ORGANIZATIONS" FOREIGN KEY ("ORGANIZATION_GUID") REFERENCES "ORGANIZATIONS" ("ORGANIZATION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORGANIZATION_CHAR_VALUES" ADD Constraint "FK_ORGANIZATIONS_CHAR_VALUES" FOREIGN KEY ("ORGANIZATION_GUID") REFERENCES "ORGANIZATIONS" ("ORGANIZATION_GUID") ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE "USER_APPLICATION_ROLES" ADD Constraint "FK_USER_APPLICATION_ROLES_USER_APPL_SUBSCRIPTION" FOREIGN KEY ("USER_APPL_SUBSCRIPTION_GUID") REFERENCES "USER_APPL_SUBSCRIPTIONS" ("USER_APPL_SUBSCRIPTION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "AUTHENTICATED_USERS" ADD Constraint "FK_UCF_AUTHENTICATED_USER_USERS" FOREIGN KEY ("USER_PROFILE_GUID") REFERENCES "USER_PROFILES" ("USER_PROFILE_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "USER_APPL_SUBSCRIPTIONS" ADD Constraint "FK_USER_PROFILES_USER_APPL_SUBSCRIPTIONS" FOREIGN KEY ("USER_PROFILE_GUID") REFERENCES "USER_PROFILES" ("USER_PROFILE_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORGANIZATIONS" ADD Constraint "FK_ORGANIZATIONS_CHANNELS" FOREIGN KEY ("CHANNEL_GUID") REFERENCES "CHANNELS" ("CHANNEL_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "CHANNEL_CLUSTERS" ADD Constraint "FK_CHANNELS_CHANNEL_CLUSTERS" FOREIGN KEY ("CHANNEL_GUID") REFERENCES "CHANNELS" ("CHANNEL_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "CHANNELS" ADD Constraint "FK_CHANNELS_COLLECTIONS" FOREIGN KEY ("COLLECTION_GUID") REFERENCES "COLLECTIONS" ("COLLECTION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ORGANIZATIONS" ADD Constraint "FK_COLLECTIONS_ORGANIZATIONS" FOREIGN KEY ("COLLECTION_GUID") REFERENCES "COLLECTIONS" ("COLLECTION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "BUSINESS_PARTNERS" ADD Constraint "FK_COLLECTIONS_BUSINESS_PARTNERS" FOREIGN KEY ("COLLECTION_GUID") REFERENCES "COLLECTIONS" ("COLLECTION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "COLLECTION_PROPERTIES" ADD Constraint "FK_COLLECTIONS_COLLECTION_PROPERTIES" FOREIGN KEY ("COLLECTION_GUID") REFERENCES "COLLECTIONS" ("COLLECTION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "COLLECTION_ITEMS" ADD Constraint "FK_COLLECTIONS_COLLECTION_ITEMS" FOREIGN KEY ("COLLECTION_GUID") REFERENCES "COLLECTIONS" ("COLLECTION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "SUB_COLLECTION_ITEMS" ADD Constraint "FK_SUB_COLLECTION_ITEMS_COLLECTIONS" FOREIGN KEY ("SUB_COLLECTION_GUID") REFERENCES "COLLECTIONS" ("COLLECTION_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ROLE_AUTHORIZATIONS" ADD Constraint "FK_APPL_COLL_ITEMS_ROLE_AUTHORIZATIONS" FOREIGN KEY ("COLLECTION_ITEM_GUID") REFERENCES "APPLICATION_COLLECTION_ITEMS" ("COLLECTION_ITEM_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "COLLECTION_ITEM_PROPERTIES" ADD Constraint "FK_COLL_ITEMS_COLL_ITEM_PROPS" FOREIGN KEY ("COLLECTION_ITEM_GUID") REFERENCES "COLLECTION_ITEMS" ("COLLECTION_ITEM_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "SUB_COLLECTION_ITEMS" ADD Constraint "FK_COLLECTION_ITEM_SUB_COLLECTION_ITEM" FOREIGN KEY ("COLLECTION_ITEM_GUID") REFERENCES "COLLECTION_ITEMS" ("COLLECTION_ITEM_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "APPLICATION_COLLECTION_ITEMS" ADD Constraint "FK_COLL_ITEM_APPL_COLL_ITEM" FOREIGN KEY ("COLLECTION_ITEM_GUID") REFERENCES "COLLECTION_ITEMS" ("COLLECTION_ITEM_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "COLLECTION_ITEM_REQUESTS" ADD Constraint "FK_COLL_ITEMS_COL_ITEM_REQS" FOREIGN KEY ("COLLECTION_ITEM_GUID") REFERENCES "COLLECTION_ITEMS" ("COLLECTION_ITEM_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "CHANNELS" ADD Constraint "FK_CHANNELS_DEFAULT_CLUSTER" FOREIGN KEY ("CHANNEL_CLUSTER_GUID") REFERENCES "CHANNEL_CLUSTERS" ("CHANNEL_CLUSTER_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "COLLECTION_ITEM_REQUESTS" ADD Constraint "FK_CURRENCIES_COLL_ITEM_REQ" FOREIGN KEY ("CURRENCY_CODE") REFERENCES "CURRENCIES" ("CURRENCY_CODE") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "APPLICATION_COLLECTION_ITEMS" ADD Constraint "FK_CURRENCIES_APPL_COLL_ITEM" FOREIGN KEY ("CURRENCY_CODE") REFERENCES "CURRENCIES" ("CURRENCY_CODE") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "CHANNELS" ADD Constraint "FK_CURRENCIES_CHANNELS" FOREIGN KEY ("CHANNEL_CURRENCY_CODE") REFERENCES "CURRENCIES" ("CURRENCY_CODE") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "COLLECTION_ITEM_REQUESTS" ADD Constraint "FK_PRICE_MODELS_COLL_ITEM_REQ" FOREIGN KEY ("PRICE_MODEL_GUID") REFERENCES "PRICE_MODELS" ("PRICE_MODEL_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "APPLICATION_COLLECTION_ITEMS" ADD Constraint "FK_PRICE_MODELS_APPL_COLL_ITEMS" FOREIGN KEY ("PRICE_MODEL_GUID") REFERENCES "PRICE_MODELS" ("PRICE_MODEL_GUID") ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE "ENTITY_SPEC_CHARACTERISTICS" ADD Constraint "FK_ENT_SPEC_ENT_SPEC_CHARS" FOREIGN KEY ("ENTITY_SPEC_GUID") REFERENCES "ENTITY_SPECIFICATION" ("ENTITY_SPEC_GUID") ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE "ENTITY_SPEC_CHAR_ENUMS" ADD Constraint "FK_ENT_SPEC_CHARS_ENTITY_SPEC_CHAR_ENUMS" FOREIGN KEY ("ENTITY_SPEC_CHAR_GUID") REFERENCES "ENTITY_SPEC_CHARACTERISTICS" ("ENTITY_SPEC_CHAR_GUID") ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE "ORGANIZATION_CHAR_VALUES" ADD Constraint "FK_ENT_SPEC_CHARS_ORG_CHAR_VALUES" FOREIGN KEY ("ENTITY_SPEC_CHAR_GUID") REFERENCES "ENTITY_SPEC_CHARACTERISTICS" ("ENTITY_SPEC_CHAR_GUID") ON UPDATE RESTRICT ON DELETE CASCADE;

ALTER TABLE "ORG_USER_CHAR_VALUES" ADD Constraint "FK_ENT_SPEC_CHARS_ORG_USER_CHAR_VALUES" FOREIGN KEY ("ENTITY_SPEC_CHAR_GUID") REFERENCES "ENTITY_SPEC_CHARACTERISTICS" ("ENTITY_SPEC_CHAR_GUID") ON UPDATE RESTRICT ON DELETE CASCADE;


